name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:  ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image ${{ matrix.arch }}
      run: |
        export BUILD_FROM="ghcr.io/home-assistant/${{ matrix.arch }}-base:3.20"
        docker build . --file Dockerfile --tag dnsmasq-dhcp:$(date +%s)
      working-directory: ./dnsmasq-dhcp
